name: to_do_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
