name: to_do_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  sqflite: ^2.2.6
  provider: ^6.0.5
  image_picker: ^1.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2
  flutter_slidable: ^4.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/json/

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/png/icon.png"
